on:
  push:
  pull_request:

jobs:
  build_wheels:
    name: Running Units Tests
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v1
      - name: Build Python Source and Wheel Distributions
        # You may pin to the exact commit or the version.
        # uses: OpenAstronomy/build-python-dist@6307a81087549def241b9c1f887208984c7b729d
        uses: OpenAstronomy/build-python-dist@v1
        with:
          pure_python_wheel: true
          test_extras: test
          test_command: pytest --pyargs test_package
